import {
  AuditLogItem,
  ClassroomItem,
  CourseCatalogItem,
  DayOfWeek,
  MemberAccount,
  SchoolAnnouncement,
  SchoolSettings,
  SubjectColor,
  SubjectItem,
  TeacherItem,
  TimeSlot,
  UserProfile,
} from './types';

export const DAYS_CONFIG: {
  key: DayOfWeek;
  thaiName: string;
  shortThai: string;
  enName: string;
  color: string;
  badgeBg: string;
}[] = [
  { key: 'monday', thaiName: 'วันจันทร์', shortThai: 'จันทร์', enName: 'Monday', color: '#eab308', badgeBg: 'bg-yellow-500/10 text-yellow-700 dark:text-yellow-400' },
  { key: 'tuesday', thaiName: 'วันอังคาร', shortThai: 'อังคาร', enName: 'Tuesday', color: '#ec4899', badgeBg: 'bg-pink-500/10 text-pink-700 dark:text-pink-400' },
  { key: 'wednesday', thaiName: 'วันพุธ', shortThai: 'พุธ', enName: 'Wednesday', color: '#10b981', badgeBg: 'bg-emerald-500/10 text-emerald-700 dark:text-emerald-400' },
  { key: 'thursday', thaiName: 'วันพฤหัสบดี', shortThai: 'พฤหัสฯ', enName: 'Thursday', color: '#f97316', badgeBg: 'bg-orange-500/10 text-orange-700 dark:text-orange-400' },
  { key: 'friday', thaiName: 'วันศุกร์', shortThai: 'ศุกร์', enName: 'Friday', color: '#0ea5e9', badgeBg: 'bg-sky-500/10 text-sky-700 dark:text-sky-400' },
  { key: 'saturday', thaiName: 'วันเสาร์', shortThai: 'เสาร์', enName: 'Saturday', color: '#8b5cf6', badgeBg: 'bg-purple-500/10 text-purple-700 dark:text-purple-400' },
  { key: 'sunday', thaiName: 'วันอาทิตย์', shortThai: 'อาทิตย์', enName: 'Sunday', color: '#ef4444', badgeBg: 'bg-red-500/10 text-red-700 dark:text-red-400' },
];

export const DEFAULT_SCHOOL_SETTINGS: SchoolSettings = {
  schoolName: 'โรงเรียนสาธิตวิทยาคม',
  schoolCode: 'SAT-10203',
  academicYear: '2569',
  semester: 'ภาคเรียนที่ 1',
  principalName: 'ดร.สมเกียรติ สถิตมั่นคง',
  academicDirector: 'อาจารย์วิชาการ ฝ่ายทะเบียน',
  contactEmail: 'academic@satit-school.ac.th',
};

export const DEFAULT_TEACHERS: TeacherItem[] = [
  { id: 'tch-1', name: 'อ.สมชาย พงษ์ศิริ', department: 'กลุ่มสาระการเรียนรู้คณิตศาสตร์', roleTitle: 'หัวหน้าหมวดคณิตศาสตร์', email: 'somchai.p@school.ac.th' },
  { id: 'tch-2', name: 'ครูวรรณา สุขใจ', department: 'กลุ่มสาระการเรียนรู้ภาษาไทย', roleTitle: 'ครูชำนาญการพิเศษ', email: 'wanna.s@school.ac.th' },
  { id: 'tch-3', name: 'ดร.กิตติศักดิ์ เจริญพร', department: 'กลุ่มสาระการเรียนรู้วิทยาศาสตร์', roleTitle: 'อาจารย์ผู้สอนฟิสิกส์', email: 'kittisak.c@school.ac.th' },
  { id: 'tch-4', name: 'ครูพรทิพย์ สว่างเนตร', department: 'กลุ่มสาระการเรียนรู้วิทยาศาสตร์', roleTitle: 'อาจารย์ผู้สอนเคมี', email: 'porntip.s@school.ac.th' },
  { id: 'tch-5', name: 'Teacher Michael Davies', department: 'กลุ่มสาระการเรียนรู้ภาษาต่างประเทศ', roleTitle: 'Native English Instructor', email: 'michael.d@school.ac.th' },
  { id: 'tch-6', name: 'อ.พงศธร รัตนพันธ์', department: 'กลุ่มสาระการเรียนรู้วิทยาศาสตร์และเทคโนโลยี', roleTitle: 'ครูผู้สอนคอมพิวเตอร์และวิทยาการคำนวณ', email: 'pongsatorn.r@school.ac.th' },
  { id: 'tch-7', name: 'ครูนงนุช บุญคง', department: 'กลุ่มสาระการเรียนรู้สังคมศึกษา', roleTitle: 'ครูผู้สอนประวัติศาสตร์/เศรษฐศาสตร์', email: 'nongnuch.b@school.ac.th' },
];

export const DEFAULT_CLASSROOMS: ClassroomItem[] = [
  { id: 'rm-1', name: 'ห้อง 421 (อาคาร 4)', building: 'อาคาร 4 ชั้น 2', type: 'general', capacity: 45 },
  { id: 'rm-2', name: 'ห้องปฏิบัติการฟิสิกส์ 1', building: 'อาคารวิทยาศาสตร์ ชั้น 3', type: 'lab', capacity: 40 },
  { id: 'rm-3', name: 'ห้องแล็บเคมี 2', building: 'อาคารวิทยาศาสตร์ ชั้น 2', type: 'lab', capacity: 40 },
  { id: 'rm-4', name: 'ห้องคอมพิวเตอร์ 3', building: 'อาคารเทคโนโลยีสารสนเทศ ชั้น 1', type: 'computer', capacity: 45 },
  { id: 'rm-5', name: 'ห้อง 224 (อาคาร 2)', building: 'อาคาร 2 ชั้น 2', type: 'general', capacity: 45 },
  { id: 'rm-6', name: 'โรงยิมเนเซียม 2', building: 'ศูนย์กีฬาและนันทนาการ', type: 'sports', capacity: 100 },
];

export const DEFAULT_COURSE_CATALOG: CourseCatalogItem[] = [
  { id: 'crs-1', code: 'ค32101', name: 'คณิตศาสตร์พื้นฐาน', department: 'คณิตศาสตร์', credits: 1.5, defaultTeacher: 'อ.สมชาย พงษ์ศิริ', defaultRoom: 'ห้อง 421 (อาคาร 4)', colorId: 'orange' },
  { id: 'crs-2', code: 'ค32201', name: 'คณิตศาสตร์เพิ่มเติม', department: 'คณิตศาสตร์', credits: 1.5, defaultTeacher: 'อ.สมชาย พงษ์ศิริ', defaultRoom: 'ห้อง 421 (อาคาร 4)', colorId: 'orange' },
  { id: 'crs-3', code: 'ว32201', name: 'ฟิสิกส์ 2', department: 'วิทยาศาสตร์', credits: 2.0, defaultTeacher: 'ดร.กิตติศักดิ์ เจริญพร', defaultRoom: 'ห้องปฏิบัติการฟิสิกส์ 1', colorId: 'blue' },
  { id: 'crs-4', code: 'ว32221', name: 'เคมี 2', department: 'วิทยาศาสตร์', credits: 1.5, defaultTeacher: 'ครูพรทิพย์ สว่างเนตร', defaultRoom: 'ห้องแล็บเคมี 2', colorId: 'teal' },
  { id: 'crs-5', code: 'ท32101', name: 'ภาษาไทย 3', department: 'ภาษาไทย', credits: 1.0, defaultTeacher: 'ครูวรรณา สุขใจ', defaultRoom: 'ห้อง 312 (อาคาร 3)', colorId: 'rose' },
  { id: 'crs-6', code: 'อ32101', name: 'ภาษาอังกฤษพื้นฐาน', department: 'ภาษาต่างประเทศ', credits: 1.0, defaultTeacher: 'Teacher Michael Davies', defaultRoom: 'ห้อง 224 (อาคาร 2)', colorId: 'purple' },
  { id: 'crs-7', code: 'ว32103', name: 'วิทยาการคำนวณ (Coding)', department: 'วิทยาศาสตร์และเทคโนโลยี', credits: 1.0, defaultTeacher: 'อ.พงศธร รัตนพันธ์', defaultRoom: 'ห้องคอมพิวเตอร์ 3', colorId: 'indigo' },
  { id: 'crs-8', code: 'ส32101', name: 'สังคมศึกษา', department: 'สังคมศึกษา', credits: 1.0, defaultTeacher: 'ครูนงนุช บุญคง', defaultRoom: 'ห้อง 331 (อาคาร 3)', colorId: 'amber' },
  { id: 'crs-9', code: 'พ32101', name: 'สุขศึกษาและพลศึกษา', department: 'สุขศึกษาและพลศึกษา', credits: 0.5, defaultTeacher: 'ครูเอกชัย ยอดรัก', defaultRoom: 'โรงยิมเนเซียม 2', colorId: 'emerald' },
];

export const DEFAULT_AUDIT_LOGS: AuditLogItem[] = [
  { id: 'log-1', timestamp: '2026-09-27 15:30:10', action: 'เผยแพร่ประกาศ', detail: 'ประกาศกำหนดการสอบกลางภาค 1/2569', actor: 'อาจารย์วิชาการ ฝ่ายทะเบียน' },
  { id: 'log-2', timestamp: '2026-09-27 14:15:22', action: 'อัปเดตหลักสูตร', detail: 'เพิ่มรายวิชาวิทยาการคำนวณ (Coding) ว32103', actor: 'อาจารย์วิชาการ ฝ่ายทะเบียน' },
  { id: 'log-3', timestamp: '2026-09-27 10:00:00', action: 'เข้าสู่ระบบหลังบ้าน', detail: 'เข้าสู่ระบบด้วยรหัส ADMIN-001', actor: 'อาจารย์วิชาการ ฝ่ายทะเบียน' },
];

export const DEFAULT_MEMBERS: MemberAccount[] = [
  {
    id: 'user-admin-1',
    memberCode: 'ADMIN-001',
    name: 'อาจารย์วิชาการ ฝ่ายทะเบียน',
    password: 'admin',
    role: 'admin',
    grade: 'กลุ่มบริหารวิชาการและวัดผล',
    schoolName: 'โรงเรียนสาธิตวิทยาคม',
    academicYear: 'ภาคเรียนที่ 1 / 2569',
    createdAt: '2026-05-15',
    avatarSeed: 'admin',
  },
  {
    id: 'user-stu-501',
    memberCode: 'STU-50101',
    name: 'กิตติพงษ์ วิริยะสกุล',
    password: '1234',
    role: 'student',
    grade: 'มัธยมศึกษาปีที่ 5/1',
    schoolName: 'โรงเรียนสาธิตวิทยาคม',
    academicYear: 'ภาคเรียนที่ 1 / 2569',
    createdAt: '2026-06-01',
    avatarSeed: 'kittipong',
  },
  {
    id: 'user-stu-403',
    memberCode: 'STU-40315',
    name: 'พิมพ์มาดา รัตนกุล',
    password: '1234',
    role: 'student',
    grade: 'มัธยมศึกษาปีที่ 4/3 (วิทย์-คณิต)',
    schoolName: 'โรงเรียนสาธิตวิทยาคม',
    academicYear: 'ภาคเรียนที่ 1 / 2569',
    createdAt: '2026-06-02',
    avatarSeed: 'pimmada',
  },
  {
    id: 'user-stu-602',
    memberCode: 'STU-60208',
    name: 'ธนากร เลิศพิชญ์',
    password: '1234',
    role: 'student',
    grade: 'มัธยมศึกษาปีที่ 6/2 (ศิลป์-ภาษา)',
    schoolName: 'โรงเรียนสาธิตวิทยาคม',
    academicYear: 'ภาคเรียนที่ 1 / 2569',
    createdAt: '2026-06-03',
    avatarSeed: 'thanakorn',
  },
];

export const DEFAULT_ANNOUNCEMENTS: SchoolAnnouncement[] = [
  {
    id: 'ann-1',
    title: '📢 ประกาศแจ้งกำหนดการสอบกลางภาค ประจำภาคเรียนที่ 1/2569',
    content: 'การสอบกลางภาคจะจัดขึ้นระหว่างวันที่ 15 - 19 ตุลาคม 2569 ขอให้นักเรียนตรวจสอบตารางสอบและเตรียมบัตรนักเรียนให้พร้อม',
    date: '28 กันยายน 2569',
    author: 'กลุ่มบริหารวิชาการ',
    priority: 'important',
  },
  {
    id: 'ann-2',
    title: '🌿 ขอความร่วมมือนักเรียนร่วมกิจกรรม Big Cleaning Day วันศุกร์นี้',
    content: 'หลังคาบเรียนที่ 6 จะมีกิจกรรมทำความสะอาดห้องเรียนและพื้นที่ส่วนกลาง ร่วมพัฒนาสิ่งแวดล้อมในโรงเรียน',
    date: '27 กันยายน 2569',
    author: 'ฝ่ายกิจการนักเรียน',
    priority: 'normal',
  },
];

export const SUBJECT_COLORS: SubjectColor[] = [
  {
    id: 'orange',
    name: 'ส้มชาไทย (Orange)',
    bg: 'bg-orange-500',
    text: 'text-orange-800 dark:text-orange-200',
    border: 'border-orange-300 dark:border-orange-800',
    accent: '#f97316',
    lightBg: 'bg-orange-50 dark:bg-orange-950/40',
  },
  {
    id: 'blue',
    name: 'ฟ้าคราม (Sky Blue)',
    bg: 'bg-sky-500',
    text: 'text-sky-800 dark:text-sky-200',
    border: 'border-sky-300 dark:border-sky-800',
    accent: '#0284c7',
    lightBg: 'bg-sky-50 dark:bg-sky-950/40',
  },
  {
    id: 'emerald',
    name: 'เขียวมรกต (Emerald)',
    bg: 'bg-emerald-500',
    text: 'text-emerald-800 dark:text-emerald-200',
    border: 'border-emerald-300 dark:border-emerald-800',
    accent: '#059669',
    lightBg: 'bg-emerald-50 dark:bg-emerald-950/40',
  },
  {
    id: 'purple',
    name: 'ม่วงลาเวนเดอร์ (Purple)',
    bg: 'bg-purple-500',
    text: 'text-purple-800 dark:text-purple-200',
    border: 'border-purple-300 dark:border-purple-800',
    accent: '#7c3aed',
    lightBg: 'bg-purple-50 dark:bg-purple-950/40',
  },
  {
    id: 'rose',
    name: 'ชมพูกุหลาบ (Rose)',
    bg: 'bg-rose-500',
    text: 'text-rose-800 dark:text-rose-200',
    border: 'border-rose-300 dark:border-rose-800',
    accent: '#e11d48',
    lightBg: 'bg-rose-50 dark:bg-rose-950/40',
  },
  {
    id: 'amber',
    name: 'ทองอำพัน (Amber)',
    bg: 'bg-amber-500',
    text: 'text-amber-800 dark:text-amber-200',
    border: 'border-amber-300 dark:border-amber-800',
    accent: '#d97706',
    lightBg: 'bg-amber-50 dark:bg-amber-950/40',
  },
  {
    id: 'indigo',
    name: 'น้ำเงินอินดิโก้ (Indigo)',
    bg: 'bg-indigo-500',
    text: 'text-indigo-800 dark:text-indigo-200',
    border: 'border-indigo-300 dark:border-indigo-800',
    accent: '#4f46e5',
    lightBg: 'bg-indigo-50 dark:bg-indigo-950/40',
  },
  {
    id: 'teal',
    name: 'เขียวหัวเป็ด (Teal)',
    bg: 'bg-teal-500',
    text: 'text-teal-800 dark:text-teal-200',
    border: 'border-teal-300 dark:border-teal-800',
    accent: '#0d9488',
    lightBg: 'bg-teal-50 dark:bg-teal-950/40',
  },
];

export const STANDARD_TIME_SLOTS: TimeSlot[] = [
  { period: 1, label: 'คาบที่ 1', startTime: '08:00', endTime: '09:00' },
  { period: 2, label: 'คาบที่ 2', startTime: '09:00', endTime: '10:00' },
  { period: 3, label: 'คาบที่ 3', startTime: '10:00', endTime: '11:00' },
  { period: 4, label: 'คาบที่ 4', startTime: '11:00', endTime: '12:00' },
  { period: 0, label: 'พักกลางวัน', startTime: '12:00', endTime: '13:00', isLunch: true },
  { period: 5, label: 'คาบที่ 5', startTime: '13:00', endTime: '14:00' },
  { period: 6, label: 'คาบที่ 6', startTime: '14:00', endTime: '15:00' },
  { period: 7, label: 'คาบที่ 7', startTime: '15:00', endTime: '16:00' },
];

export const DEFAULT_USER_PROFILE: UserProfile = {
  name: 'กิตติพงษ์ วิริยะสกุล',
  grade: 'มัธยมศึกษาปีที่ 5/1',
  schoolName: 'โรงเรียนสาธิตวิทยาคม',
  academicYear: 'ภาคเรียนที่ 1 / 2569',
  theme: 'light',
  showWeekend: false,
};

export const INITIAL_SAMPLE_SUBJECTS: SubjectItem[] = [
  // Monday
  {
    id: 'sub-mon-1',
    code: 'ค32101',
    name: 'คณิตศาสตร์พื้นฐาน',
    day: 'monday',
    startTime: '08:00',
    endTime: '09:00',
    room: 'ห้อง 421 (อาคาร 4)',
    teacher: 'อ.สมชาย พงษ์ศิริ',
    colorId: 'orange',
    notes: 'เตรียมหนังสือและสมุดกราฟมาด้วย',
  },
  {
    id: 'sub-mon-2',
    code: 'ท32101',
    name: 'ภาษาไทย 3',
    day: 'monday',
    startTime: '09:00',
    endTime: '10:00',
    room: 'ห้อง 312 (อาคาร 3)',
    teacher: 'ครูวรรณา สุขใจ',
    colorId: 'rose',
    notes: 'ท่องอาขยานบทที่ 2 สัปดาห์หน้า',
  },
  {
    id: 'sub-mon-3',
    code: 'ว32201',
    name: 'ฟิสิกส์ 2',
    day: 'monday',
    startTime: '10:00',
    endTime: '12:00',
    room: 'ห้องปฏิบัติการฟิสิกส์ 1',
    teacher: 'ดร.กิตติศักดิ์ เจริญพร',
    colorId: 'blue',
    notes: 'มีทดลองเรื่องการเคลื่อนที่แบบฮาร์มอนิกอย่างง่าย',
  },
  {
    id: 'sub-mon-4',
    code: 'อ32101',
    name: 'ภาษาอังกฤษพื้นฐาน',
    day: 'monday',
    startTime: '13:00',
    endTime: '14:00',
    room: 'ห้อง 224 (อาคาร 2)',
    teacher: 'Teacher Michael Davies',
    colorId: 'purple',
    notes: 'Unit 3 Vocabulary Quiz',
  },
  {
    id: 'sub-mon-5',
    code: 'ส32101',
    name: 'สังคมศึกษา (ประวัติศาสตร์)',
    day: 'monday',
    startTime: '14:00',
    endTime: '15:00',
    room: 'ห้อง 331 (อาคาร 3)',
    teacher: 'ครูนงนุช บุญคง',
    colorId: 'amber',
  },

  // Tuesday
  {
    id: 'sub-tue-1',
    code: 'ว32221',
    name: 'เคมี 2',
    day: 'tuesday',
    startTime: '08:00',
    endTime: '10:00',
    room: 'ห้องแล็บเคมี 2',
    teacher: 'ครูพรทิพย์ สว่างเนตร',
    colorId: 'teal',
    notes: 'สวมเสื้อกาวน์และแว่นตาป้องกันสารเคมี',
  },
  {
    id: 'sub-tue-2',
    code: 'ว32103',
    name: 'วิทยาการคำนวณ (Coding)',
    day: 'tuesday',
    startTime: '10:00',
    endTime: '12:00',
    room: 'ห้องคอมพิวเตอร์ 3',
    teacher: 'อ.พงศธร รัตนพันธ์',
    colorId: 'indigo',
    notes: 'เขียนโปรแกรม Data Analysis ด้วย Python',
  },
  {
    id: 'sub-tue-3',
    code: 'ค32201',
    name: 'คณิตศาสตร์เพิ่มเติม',
    day: 'tuesday',
    startTime: '13:00',
    endTime: '14:00',
    room: 'ห้อง 421 (อาคาร 4)',
    teacher: 'อ.สมชาย พงษ์ศิริ',
    colorId: 'orange',
  },
  {
    id: 'sub-tue-4',
    code: 'พ32101',
    name: 'สุขศึกษาและพลศึกษา (บาสเกตบอล)',
    day: 'tuesday',
    startTime: '14:00',
    endTime: '15:00',
    room: 'โรงยิมเนเซียม 2',
    teacher: 'ครูเอกชัย ยอดรัก',
    colorId: 'emerald',
    notes: 'แต่งกายชุดพละ รองเท้าผ้าใบให้เรียบร้อย',
  },

  // Wednesday
  {
    id: 'sub-wed-1',
    code: 'อ32201',
    name: 'ภาษาอังกฤษเพื่อการสื่อสาร',
    day: 'wednesday',
    startTime: '08:00',
    endTime: '09:00',
    room: 'ห้อง 224 (อาคาร 2)',
    teacher: 'Teacher Sarah Miller',
    colorId: 'purple',
    notes: 'Group Presentation 5 นาที',
  },
  {
    id: 'sub-wed-2',
    code: 'ว32241',
    name: 'ชีววิทยา 2',
    day: 'wednesday',
    startTime: '09:00',
    endTime: '11:00',
    room: 'ห้องปฏิบัติการชีววิทยา',
    teacher: 'ครูจริยา เพชรรัตน์',
    colorId: 'emerald',
    notes: 'ศึกษาโครงสร้างเซลล์พืชด้วยกล้องจุลทรรศน์',
  },
  {
    id: 'sub-wed-3',
    code: 'ท32101',
    name: 'ภาษาไทย 3 (การเขียนเชิงวิชาการ)',
    day: 'wednesday',
    startTime: '11:00',
    endTime: '12:00',
    room: 'ห้อง 312 (อาคาร 3)',
    teacher: 'ครูวรรณา สุขใจ',
    colorId: 'rose',
  },
  {
    id: 'sub-wed-4',
    code: 'ก32901',
    name: 'กิจกรรมแนะแนว',
    day: 'wednesday',
    startTime: '13:00',
    endTime: '14:00',
    room: 'หอประชุมใหญ่',
    teacher: 'ครูมาลี เจริญธรรม',
    colorId: 'amber',
    notes: 'สำรวจความถนัดเพื่อเตรียมตัวเข้ามหาวิทยาลัย',
  },
  {
    id: 'sub-wed-5',
    code: 'ก32902',
    name: 'กิจกรรมชุมนุม (Club)',
    day: 'wednesday',
    startTime: '14:00',
    endTime: '15:00',
    room: 'ห้องชมรมดนตรีสากล',
    teacher: 'อ.วิชัย ดนตรีการ',
    colorId: 'teal',
  },

  // Thursday
  {
    id: 'sub-thu-1',
    code: 'ค32201',
    name: 'คณิตศาสตร์เพิ่มเติม',
    day: 'thursday',
    startTime: '08:00',
    endTime: '10:00',
    room: 'ห้อง 421 (อาคาร 4)',
    teacher: 'อ.สมชาย พงษ์ศิริ',
    colorId: 'orange',
    notes: 'แบบฝึกหัดเรื่องเมทริกซ์และดีเทอร์มิแนนต์',
  },
  {
    id: 'sub-thu-2',
    code: 'ส32102',
    name: 'สังคมศึกษา (เศรษฐศาสตร์)',
    day: 'thursday',
    startTime: '10:00',
    endTime: '11:00',
    room: 'ห้อง 331 (อาคาร 3)',
    teacher: 'ครูนงนุช บุญคง',
    colorId: 'amber',
  },
  {
    id: 'sub-thu-3',
    code: 'ศ32101',
    name: 'ศิลปะและทัศนศิลป์',
    day: 'thursday',
    startTime: '11:00',
    endTime: '12:00',
    room: 'ห้องศิลปะ 1',
    teacher: 'ครูอภิสิทธิ์ วาดวิจิตร',
    colorId: 'rose',
    notes: 'นำสีน้ำและกระดาษ 100 ปอนด์มาด้วย',
  },
  {
    id: 'sub-thu-4',
    code: 'ว32201',
    name: 'ฟิสิกส์ 2 (ติวเข้มและโจทย์)',
    day: 'thursday',
    startTime: '13:00',
    endTime: '15:00',
    room: 'ห้อง 425 (อาคาร 4)',
    teacher: 'ดร.กิตติศักดิ์ เจริญพร',
    colorId: 'blue',
  },

  // Friday
  {
    id: 'sub-fri-1',
    code: 'ว32221',
    name: 'เคมี 2 (สรุปผลการทดลอง)',
    day: 'friday',
    startTime: '08:00',
    endTime: '09:00',
    room: 'ห้อง 423 (อาคาร 4)',
    teacher: 'ครูพรทิพย์ สว่างเนตร',
    colorId: 'teal',
  },
  {
    id: 'sub-fri-2',
    code: 'อ32101',
    name: 'ภาษาอังกฤษพื้นฐาน',
    day: 'friday',
    startTime: '09:00',
    endTime: '10:00',
    room: 'ห้อง 224 (อาคาร 2)',
    teacher: 'Teacher Michael Davies',
    colorId: 'purple',
  },
  {
    id: 'sub-fri-3',
    code: 'ค32101',
    name: 'คณิตศาสตร์พื้นฐาน',
    day: 'friday',
    startTime: '10:00',
    endTime: '11:00',
    room: 'ห้อง 421 (อาคาร 4)',
    teacher: 'อ.สมชาย พงษ์ศิริ',
    colorId: 'orange',
  },
  {
    id: 'sub-fri-4',
    code: 'ง32101',
    name: 'การงานอาชีพและการเป็นผู้ประกอบการ',
    day: 'friday',
    startTime: '11:00',
    endTime: '12:00',
    room: 'ห้องปฏิบัติการธุรกิจ',
    teacher: 'ครูศิริพร บุญเสริม',
    colorId: 'indigo',
  },
  {
    id: 'sub-fri-5',
    code: 'ก32903',
    name: 'กิจกรรมเพื่อสังคมและสาธารณประโยชน์',
    day: 'friday',
    startTime: '13:00',
    endTime: '14:00',
    room: 'ห้องโฮมรูม',
    teacher: 'ครูประจำชั้น ม.5/1',
    colorId: 'emerald',
  },
  {
    id: 'sub-fri-6',
    code: 'อบ32001',
    name: 'โฮมรูมและประเมินผลประจำสัปดาห์',
    day: 'friday',
    startTime: '14:00',
    endTime: '15:00',
    room: 'ห้อง 421 (อาคาร 4)',
    teacher: 'ครูประจำชั้น ม.5/1',
    colorId: 'amber',
    notes: 'สรุปการส่งงานและการเตรียมสอบกลางภาค',
  },
];
